---
- name: Ensure common packages are installed
  yum: pkg={{ item }} state=installed update_cache=yes 
  with_items:
    - python-pycurl
  sudo: true
  tags: postgres_common


- name: install the latest version of Postgres from the ABS_PostgreSQL_11 repo
  yum:
    name: postgresql11
    enablerepo: ABS_PostgreSQL_Official_PostgreSQL_11
    state: present



- name: Ensure packages are installed
  yum: pkg={{ item }}
  with_items:
    - postgresql{{ pg_version }}-server
    - python-psycopg2
  register: db_setup
  environment: '{{ pg_proxy_env }}'
  sudo: true
  tags: postgres_packages

- 
- name: Update pg_hba.conf file
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/{{ pg_version }}/{{ pg_cluster }}/pg_hba.conf owner={{ pg_admin_user }} group={{ pg_admin_user }} mode=0640
  notify: restart postgresql
  sudo: true
  tags: postgres_config

- name: Update postgres.conf file
  template: src=master.conf.j2 dest=/var/lib/pgsql/{{ pg_version }}/{{ pg_cluster }}/postgresql.conf owner={{ pg_admin_user }} group={{ pg_admin_user }} mode=0644
  sudo: true
  notify: restart postgresql
  tags: postgres_config


- include: extensions_common.yml
  tags: postgres_extensions

- meta: flush_handlers

- name: ensure postgresql server is started
  service:
    name: postgresql
    state: started
    enabled: yes
  tags: postgres_start

